variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEXAMPLE_KEY_REPLACE_WITH_YOUR_ACTUAL_KEY
      groups:
        - sudo
        - docker
storage:
  files:
    - path: /etc/hostname
      mode: 0644
      contents:
        inline: helios-coreos
    - path: /etc/sysctl.d/20-silence-audit.conf
      mode: 0644
      contents:
        inline: |
          # Reduce audit noise
          kernel.printk=4
    - path: /etc/modules-load.d/k8s.conf
      mode: 0644
      contents:
        inline: |
          overlay
          br_netfilter
    - path: /etc/sysctl.d/k8s.conf
      mode: 0644
      contents:
        inline: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
systemd:
  units:
    - name: docker.service
      enabled: true
