name: Build Fedora CoreOS Base

on:
  push:
    branches: [ main ]
    paths:
      - 'scripts/build/create_coreos_base.sh'
      - 'scripts/provision/coreos_config.yaml'
  workflow_dispatch:
    inputs:
      coreos_version:
        description: 'Fedora CoreOS version'
        required: false
        default: ''

jobs:
  build-coreos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install OrbStack and dependencies
        run: |
          brew install orbstack jq qemu butane coreutils
          orb install
      
      - name: Setup build environment
        run: |
          mkdir -p manifests
          if [ ! -f manifests/image_catalog.json ]; then
            echo '[]' > manifests/image_catalog.json
          fi
          
      - name: Build Fedora CoreOS base image
        run: |
          chmod +x scripts/build/create_coreos_base.sh
          scripts/build/create_coreos_base.sh
          
      - name: Update image catalog
        run: |
          BUILD_ID=$(ls output-fedora-coreos/*.manifest.json | sort | tail -1 | xargs cat | jq -r '.build_id')
          MANIFEST_FILE="output-fedora-coreos/fedora-coreos-${BUILD_ID}.manifest.json"
          jq -s '.[0] + [.[1]]' manifests/image_catalog.json "$MANIFEST_FILE" > manifests/image_catalog.json.new
          mv manifests/image_catalog.json.new manifests/image_catalog.json
          
      - name: Create latest symlink
        run: |
          cd output-fedora-coreos
          BUILD_ID=$(ls *.manifest.json | sort | tail -1 | xargs cat | jq -r '.build_id')
          ln -sf "fedora-coreos-${BUILD_ID}.tar.gz" "fedora-coreos-latest.tar.gz"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fedora-coreos-images
          path: |
            output-fedora-coreos/*.tar.gz
            output-fedora-coreos/*.manifest.json
            manifests/image_catalog.json
