name: Build K3d Cluster Image

on:
  push:
    branches: [ main ]
    paths:
      - 'scripts/build/create_k3d_cluster.sh'
      - 'scripts/provision/k3d_bootstrap.sh'
  workflow_run:
    workflows: ["Build Fedora CoreOS Base"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-k3d:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install OrbStack
        run: |
          brew install orbstack jq
          orb install
      
      - name: Download base image
        uses: actions/download-artifact@v3
        with:
          name: fedora-coreos-images
          path: base-images
      
      - name: Find latest base image
        id: find-base
        run: |
          BASE_IMAGE_PATH=$(find base-images -name "fedora-coreos-latest.tar.gz" -o -name "fedora-coreos-*.tar.gz" | sort | tail -1)
          echo "base_image_path=${BASE_IMAGE_PATH}" >> $GITHUB_OUTPUT
          
      - name: Build K3d cluster image
        run: |
          chmod +x scripts/build/create_k3d_cluster.sh
          scripts/build/create_k3d_cluster.sh ${{ steps.find-base.outputs.base_image_path }}
          
      - name: Update image catalog
        run: |
          mkdir -p manifests
          if [ ! -f manifests/image_catalog.json ]; then
            echo '[]' > manifests/image_catalog.json
          fi
          
          BUILD_ID=$(ls output-k3d-cluster/*.manifest.json | sort | tail -1 | xargs cat | jq -r '.build_id')
          MANIFEST_FILE="output-k3d-cluster/k3d-cluster-${BUILD_ID}.manifest.json"
          jq -s '.[0] + [.[1]]' manifests/image_catalog.json "$MANIFEST_FILE" > manifests/image_catalog.json.new
          mv manifests/image_catalog.json.new manifests/image_catalog.json
          
      - name: Create latest symlink
        run: |
          cd output-k3d-cluster
          BUILD_ID=$(ls *.manifest.json | sort | tail -1 | xargs cat | jq -r '.build_id')
          ln -sf "k3d-cluster-${BUILD_ID}.tar.gz" "k3d-cluster-latest.tar.gz"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: k3d-cluster-images
          path: |
            output-k3d-cluster/*.tar.gz
            output-k3d-cluster/*.manifest.json
            manifests/image_catalog.json
